# -*- coding: utf-8 -*-
"""用語を足す（その6: USD と Solaris／煙と炎の計算）。"""

CATEGORIES_NEW = [
    ("usd", "USD と Solaris", "Solaris（LOP）で出てくる、USD の舞台の言葉。"),
]

ADD = {
    "usd": [
        {"term": "USD ステージ / Stage", "reading": "ユーエスディーステージ",
         "def": "USD の舞台全体。いくつものレイヤーを重ねた結果として見えている、1つのシーン。Solaris の箱は、このステージを少しずつ書き換えていく。",
         "related": "USD, レイヤー（USD）"},
        {"term": "プリム / Prim", "reading": "プリム",
         "def": "USD のステージに置かれる1つ1つの要素。形・光・カメラ・材質・入れ物（Xform）など。/world/geo/box のようなパスで場所を表す。SOP のプリミティブとは別物。"},
        {"term": "レイヤー（USD） / Layer", "reading": "レイヤー",
         "def": "USD の編集を書き込んだ1枚の紙。何枚も重ねて1つのステージになる。上の紙の書き込みが、下の紙より強い。"},
        {"term": "オピニオン / Opinion", "reading": "オピニオン",
         "def": "あるレイヤーが、ある属性に対して書いた値。同じ属性に複数のオピニオンがあると、強い方が勝つ。"},
        {"term": "コンポジション / Composition", "reading": "コンポジション",
         "def": "レイヤー・参照・バリアントなどを組み合わせて、最終的なステージを作る仕組み。強さの順番（LIVRPS）が決まっている。"},
        {"term": "LIVRPS", "reading": "リブアールピーエス",
         "def": "USD で、どの書き込みが勝つかの強さの順番。Local・Inherits・VariantSets・References・Payloads・Specializes の頭文字。左ほど強い。"},
        {"term": "参照（USD） / Reference", "reading": "さんしょう",
         "def": "別の USD ファイルの中身を、コピーせずに指し示して読み込むこと。元のファイルを直すと、参照している所すべてに反映される。"},
        {"term": "ペイロード / Payload", "reading": "ペイロード",
         "def": "あとから読み込むことにできる参照。重い部品を、必要になるまで読み込まずに置いておける。"},
        {"term": "バリアント / Variant", "reading": "バリアント",
         "def": "1つの物の中に持たせた、切り替えられる別案。色違い・形違い・細かさ違いなどを1つにまとめる。"},
        {"term": "Kind", "reading": "カインド",
         "def": "プリムの役割の札。component（部品）・assembly（組み立て）・group などがあり、選択や整理の単位になる。"},
        {"term": "Purpose", "reading": "パーパス",
         "def": "プリムの用途の札。render（本番の描画）・proxy（軽い代わり）・guide（目印）など。ビューポートとレンダーで出し分けられる。"},
        {"term": "インスタンサブル / Instanceable", "reading": "インスタンサブル",
         "def": "同じ参照を持つプリムの中身を共有させる印。大量に置いても、メモリが増えにくい。"},
        {"term": "Hydra", "reading": "ハイドラ",
         "def": "USD のステージを描くための共通の仕組み。ビューポートや Karma は、Hydra を通してステージを描く。"},
        {"term": "Render Settings / Product / Var", "reading": "レンダーセッティング",
         "def": "USD でレンダリングの設定を表す3つのプリム。Settings が全体（カメラ・解像度）、Product が書き出す画像1枚、Var がその中の AOV 1つ。"},
        {"term": "Cryptomatte", "reading": "クリプトマット",
         "def": "物や材質ごとに色分けされた ID の画像。合成のときに、あとから好きな物だけを切り抜ける。"},
    ],
    "simulation": [
        {"term": "マイクロソルバ / Microsolver", "reading": "マイクロソルバ",
         "def": "1つの仕事だけをする小さな解き手（運ぶ・減らす・ぼかす・浮かせる など）。Pyro や FLIP の中身は、これらの組み合わせでできている。"},
        {"term": "移流 / Advection", "reading": "いりゅう",
         "def": "流れに乗って、濃さや温度が運ばれること。煙のシミュレーションで毎ステップ行う、いちばん基本の計算。"},
        {"term": "浮力 / Buoyancy", "reading": "ふりょく",
         "def": "まわりより軽い（熱い）ものが浮き上がる力。煙の計算では、温度の高い所に上向きの速度を足して表す。"},
        {"term": "渦度の閉じ込め / Vortex Confinement", "reading": "うずどのとじこめ",
         "def": "計算の途中でなまって消えてしまう小さな渦を、回転を強めて取り戻す工夫。煙の細かさを保つ。"},
        {"term": "燃焼 / Combustion", "reading": "ねんしょう",
         "def": "燃料が燃えて、熱と煙と気体を出すこと。Pyro では、発火温度を超えた所で燃料を減らし、温度を上げて表す。"},
        {"term": "発火温度 / Ignition Temperature", "reading": "はっかおんど",
         "def": "燃料が燃え始める温度。これより低い所では、燃料があっても燃えない。"},
        {"term": "スート / Soot", "reading": "スート",
         "def": "燃えたあとに出る煤（すす）の煙。Pyro では density とは別に、黒い煙として扱うことがある。"},
        {"term": "温度場 / Temperature Field", "reading": "おんどば",
         "def": "場所ごとの温度を持つボリューム。浮力の強さや、炎の色（黒体放射）を決める。"},
        {"term": "速度場 / Velocity Field", "reading": "そくどば",
         "def": "場所ごとの流れの向きと速さを持つボリューム（vel）。これに乗って、煙の濃さや温度が運ばれる。"},
        {"term": "圧力投影 / Pressure Projection", "reading": "あつりょくとうえい",
         "def": "流れが「どこでも湧き出さない・吸い込まない（発散0）」ようにする計算。煙や水が縮んだり増えたりしないようにする要。",
         "related": "発散"},
    ],
}
