# -*- coding: utf-8 -*-
"""ノード解説を足す（その3: 粒・力・シム補強・地形・リグ・毛・シーン・出力・材質）。"""

ADD = {
    "pop": [
        {"name": "popsolver::2.0", "kind": "DOP",
         "one": "粒を1フレームずつ進める本体。",
         "what": "POP のネットワークで、実際に時間を進めるのはこの箱。上に足した力やグループの指示を全部受けて、位置と速度を更新する。細かく刻みたいときは Max Substeps を上げる。",
         "params": [["substeps", "1フレームを最大何回に刻むか"], ["minimumsubsteps", "最低何回刻むか"], ["timescale", "時間の進み方"]],
         "gotcha": "DOP の中で表示フラグが付いている箱が解かれる。ソルバに付け忘れると、粒が1つも出ないまま終わる（実験079）。",
         "exps": ["079"]},
        {"name": "popsource", "kind": "DOP",
         "one": "粒を生み出す口。",
         "what": "SOP の点を受け取って、そこから粒を出す。Emission Type で、点の上に1粒ずつ置くのか、面の上に散らすのかが変わる。",
         "params": [["emittype", "出し方（Points / All Points など）"], ["soppath", "元になる SOP"], ["impulseactivation", "1フレームに出すかどうか"], ["const_activation", "毎秒いくつ出すか"]],
         "gotcha": "Emission Type を All Points にすると Impulse Count が効かず、1フレームに点の数だけ出る。数を指定したいときは Points にする（実験079）。",
         "exps": ["079", "080"]},
        {"name": "popobject", "kind": "DOP",
         "one": "粒の入れ物そのもの。",
         "what": "どこに粒を貯めるかを決める箱。popnet を作ると自動で置かれるので、直接触ることは少ない。名前を変えて複数の群れを分けたいときに使う。",
         "params": [["object_name", "名前"], ["createframe", "できるフレーム"], ["initial_geo", "最初から入れておく形"]]},
        {"name": "popdrag", "kind": "DOP",
         "one": "空気の抵抗で粒を遅くする。",
         "what": "速いほど強く効くので、落ち続けても速度が頭打ちになる。火花や雪のように、ふわりと落とすときに足す。",
         "params": [["airresist", "空気の抵抗の強さ"], ["windvelocity", "風の速度"], ["ignoremass", "重さを無視する"]],
         "exps": ["079"]},
        {"name": "popattract", "kind": "DOP",
         "one": "決めた場所へ粒を引き寄せる。",
         "what": "目標の位置へ向かう力を足す。Attraction Type で、位置に引くのか速度を合わせるのかを選ぶ。",
         "params": [["goal", "目標の位置"], ["goalvel", "目標の速度"], ["attracttype", "引き方"]]},
        {"name": "popcurveforce", "kind": "DOP",
         "one": "線に沿って粒を流す。",
         "what": "渡した曲線の向きに粒を運ぶ。煙や粒を決まった道筋で動かしたいときに使う。",
         "params": [["soppath", "道になる線"], ["scalesuction", "線へ吸い寄せる強さ"], ["scalefollow", "線に沿って流す強さ"]]},
        {"name": "popcollisiondetect", "kind": "DOP",
         "one": "ぶつかったときの振る舞いを決める。",
         "what": "跳ね返るか、止まるか、消えるか、すべるか。跳ね返りの強さと摩擦もここで決める。",
         "params": [["response", "ぶつかったあとどうするか"], ["collider", "ぶつかる相手"], ["creategroup", "当たった粒をグループにする"]],
         "exps": ["080"]},
        {"name": "popgroup", "kind": "DOP",
         "one": "条件に合う粒に名前を付ける。",
         "what": "速度・年齢・位置などで粒を選んでグループにする。そのグループにだけ力を効かせる、といった分け方ができる。",
         "params": [["groupname", "付ける名前"], ["enablerule", "選ぶ条件を使う"], ["rulecode", "条件の式"]]},
        {"name": "popkill", "kind": "DOP",
         "one": "条件に合う粒を消す。",
         "what": "床より下へ行った粒、遅くなりすぎた粒などを消す。数が減るので、そのぶん計算も軽くなる。",
         "params": [["enablerule", "条件を使う"], ["rulecode", "消す条件の式"]]},
        {"name": "popreplicate", "kind": "DOP",
         "one": "粒から粒を生む。",
         "what": "飛んでいる粒を親にして、そこから子の粒を出す。火花の尾や、はじけて散る表現に使う。",
         "params": [["impulserate", "1回に生む数"], ["constantrate", "毎秒生む数"], ["life", "子の寿命"]]},
        {"name": "popspin", "kind": "DOP",
         "one": "粒を回す。",
         "what": "粒そのものの向きを回転させる。粒に形を複製して並べたとき、この回転が見た目に出る。",
         "params": [["axis", "回る軸"], ["spinspeed", "回る速さ"], ["localspin", "粒の向きを基準にする"]]},
        {"name": "popspeedlimit", "kind": "DOP",
         "one": "速さの上限と下限を決める。",
         "what": "速くなりすぎた粒を抑える。計算が破綻するのを防ぐ安全装置としても使う。",
         "params": [["speedmax", "上限"], ["speedmin", "下限"]]},
    ],
    "force": [
        {"name": "gravity", "kind": "DOP",
         "one": "重力をかける。",
         "what": "つないだものすべてに、一定の向きの加速度を足す。既定は下向きで、地球のおよその値が入っている。",
         "params": [["force", "向きと強さ"], ["samplemode", "どこで力を測るか"]],
         "exps": ["080"]},
        {"name": "drag", "kind": "DOP",
         "one": "動きにブレーキをかける。",
         "what": "目標の速度へ向けて減速させる。目標を0にすると、だんだん止まる。回転にも別々に効かせられる。",
         "params": [["vel", "目標の速度"], ["angvel", "目標の回転速度"], ["ignoremass", "重さを無視する"]]},
        {"name": "fan", "kind": "DOP",
         "one": "扇風機のように、円錐の範囲へ風を送る。",
         "what": "位置と向きと広がり角を決めると、その円錐の中にだけ風が当たる。一方向の風より、局所的に吹かせたいときに使う。",
         "params": [["t", "置く位置"], ["direction", "吹く向き"], ["coneangle", "広がりの角度"]]},
        {"name": "groundplane", "kind": "DOP",
         "one": "無限に広がる床を置く。",
         "what": "落ちてくるものを受け止める。見えているのは目印の格子だけで、当たり判定は平面全体に広がっている。",
         "params": [["grid_size", "目印の大きさ"], ["t", "高さ"]],
         "gotcha": "床を置いただけでは効かない。merge でまとめ、その merge に表示フラグを付けないと、粒が床をすり抜ける（実験080）。",
         "exps": ["080"]},
        {"name": "staticobject", "kind": "DOP",
         "one": "動かない障害物を置く。",
         "what": "SOP の形を、ぶつかる相手として持ち込む。自分は動かないので、計算は軽い。",
         "params": [["soppath", "元になる SOP"], ["animategeo", "形が変わるものとして扱う"], ["friction", "摩擦"], ["bounce", "跳ね返り"]],
         "gotcha": "形が変わらないなら Deforming を切ったままにする。切っているほうが速い（実験069）。",
         "exps": ["069"]},
        {"name": "rbdobject", "kind": "DOP",
         "one": "ぶつかって動く硬い物を置く。",
         "what": "重さ・初速・跳ね返りを持った剛体として持ち込む。古い作り方で、いまは rbdbulletsolver でまとめて扱うことが多い。",
         "params": [["soppath", "元になる SOP"], ["inheritvelocity", "点の速度を初速にする"], ["bounce", "跳ね返り"]]},
    ],
    "sim": [
        {"name": "dopimport", "kind": "SOP",
         "one": "シミュレーションの結果を SOP へ持ち帰る。",
         "what": "DOP の中で解いた結果を、形として取り出す。Object Mask でどの物を持ってくるかを絞る。",
         "params": [["doppath", "DOP ネットワーク"], ["objpattern", "持ってくる物の名前"], ["importstyle", "取り出し方"]],
         "gotcha": "Object Mask を * にすると、床などぶつかる相手まで持ってきてしまう。実験080では点が100から200に、面が0から81に増えた。名前で絞る。",
         "exps": ["080"]},
        {"name": "dopnet", "kind": "SOP",
         "one": "シミュレーションを組む部屋。",
         "what": "この中に力やソルバを並べる。1フレームあたり何回刻むか（Substeps）もここで決める。",
         "params": [["substep", "1フレームの刻み数"], ["timestep", "1回ぶんの時間"], ["resimulate", "計算をやり直す"]]},
        {"name": "vellumdrape", "kind": "SOP",
         "one": "布を落として自然に垂らす。",
         "what": "平らな布を対象の上に落として、しわの寄った初期状態を作る。服を着せる前の下ごしらえ。",
         "params": [["freezeframe", "この形で止める"], ["dofreeze", "止める"]]},
        {"name": "vellumpostprocess", "kind": "SOP",
         "one": "布の計算結果を仕上げる。",
         "what": "粗い布で解いた結果を細かく割り直したり、めり込みをほどいたりする。軽く解いてから見た目を上げる流れで使う。",
         "params": [["subdivide", "細かく割る"], ["depth", "割る回数"], ["dodetangle", "絡みをほどく"]]},
        {"name": "particlefluidsurface", "kind": "SOP",
         "one": "液体の粒から表面を作る。",
         "what": "ばらばらの粒を、つながった面に変える。Point Radius Scale を上げるほど粒が太って一体になり、下げるほど粒立って見える。",
         "params": [["particlesep", "粒の間隔"], ["radiusscale", "粒の太らせ方"], ["surfdistance", "表面の位置をずらす"]],
         "exps": ["019"]},
        {"name": "rbdconstraintproperties", "kind": "SOP",
         "one": "破片どうしのつなぎ目の強さを決める。",
         "what": "どれくらいの力で外れるか、曲がるか、伸びるかを決める。ここを強くすると壊れにくく、弱くすると触れただけで崩れる。",
         "params": [["constrainttype", "つなぎ方の種類"], ["strength", "外れるまでの強さ"], ["angularstrength", "曲げに対する強さ"]],
         "gotcha": "強さを上げすぎると、ぶつける前に自分の重さで崩れる形も出る。実験085では、何もぶつけなくても崩れる値があった。",
         "exps": ["085"]},
        {"name": "rbdconfigure", "kind": "SOP",
         "one": "硬い物の重さや当たり方を決める。",
         "what": "密度から重さを出し、当たり判定の形を選ぶ。細かい形のまま当てると重いので、箱や凸包で代えることが多い。",
         "params": [["unitmass", "重さ"], ["boundingtype", "当たり判定の形"], ["active1", "動くか、動かないか"]]},
        {"name": "rbdpaint", "kind": "SOP",
         "one": "壊れやすさを筆で塗る。",
         "what": "画面上でなぞった所だけ、割れ方やつなぎ目の強さを変える。ここから割れてほしい、という指定を手でできる。",
         "params": [["group", "塗る対象"], ["explodedview", "破片を離して見る"]]},
        {"name": "pyrobakevolume", "kind": "SOP",
         "one": "煙や炎の見た目を決める。",
         "what": "温度や煙の濃さから、色と明るさを作る。炎の色味を変えるのはたいていこの箱。",
         "params": [["shop_materialpath", "材質の割り当て"], ["setmaxres", "画面表示の上限"]],
         "exps": ["026"]},
    ],
    "terrain": [
        {"name": "heightfield_blur", "kind": "SOP",
         "one": "地形をなだらかにする。",
         "what": "高さをならして、角のとれた地形にする。Radius が大きいほど広くならす。削る前の下地作りにも使う。",
         "params": [["radius", "ならす範囲"], ["iterations", "繰り返す回数"], ["masklayer", "効かせる範囲"]]},
        {"name": "heightfield_slump", "kind": "SOP",
         "one": "急な斜面の土を崩して落とす。",
         "what": "安息角より急な所の土が、下へ滑り落ちる。崖の下に土が溜まった形になる。erode より軽い。",
         "params": [["repose_angle", "これより急だと崩れる角度"], ["iterations", "繰り返す回数"], ["spread_rate", "広がる速さ"]]},
        {"name": "heightfield_maskbyfeature", "kind": "SOP",
         "one": "地形の特徴から塗り分けを作る。",
         "what": "傾き・高さ・向き・曲がり具合などで、地形に「ここ」という印を作る。その印を使って、草を生やす場所や雪の積もる場所を決める。",
         "params": [["maskbyslope", "傾きで選ぶ"], ["min_slopeangle", "傾きの下限"], ["maskbyheight", "高さで選ぶ"]],
         "exps": ["035"]},
        {"name": "heightfield_scatter", "kind": "SOP",
         "one": "地形の上に点をばらまく。",
         "what": "印の濃さに応じて点を散らす。そこに木や草を複製して並べる。",
         "params": [["npts", "点の数"], ["layer", "使う印"], ["densityscale", "濃さ"]]},
        {"name": "heightfield_project", "kind": "SOP",
         "one": "形を地形に押し当てて印にする。",
         "what": "置いた形の影になる所を、印として地形に描き込む。道や建物の跡をつけるときに使う。",
         "params": [["maskdir", "押し当てる向き"], ["heightlayer", "高さの層"]]},
    ],
    "rig": [
        {"name": "kinefx::rigpose", "kind": "SOP",
         "one": "骨をつまんで動かす。",
         "what": "画面のハンドルで関節を回し、姿勢を作る。作った姿勢はこの箱が覚えている。",
         "params": [["worldspace", "世界の座標で動かす"], ["bakepose", "いまの姿勢を焼き込む"]],
         "exps": ["051"]},
        {"name": "kinefx::skeleton", "kind": "SOP",
         "one": "骨を組み立てる。",
         "what": "画面上で関節を置いて、つなげていく。腕や脚の骨組みをここで作る。",
         "params": [["stashinput", "入力を抱え込む"], ["transferanimation", "入力の動きを引き継ぐ"]],
         "exps": ["051"]},
        {"name": "bonedeform", "kind": "SOP",
         "one": "骨の動きに皮をついていかせる。",
         "what": "骨・元の姿勢・動いた姿勢の3つを受け取り、皮を変形させる。Skinning Method で、関節の内側のつぶれ方が変わる。",
         "params": [["method", "変形のやり方"], ["dqblendattrib", "2つのやり方を混ぜる割合"]],
         "gotcha": "Linear だと関節の内側がつぶれ、Dual Quaternion だと膨らむ。実験053・054で、同じ角度でも体積の残り方が変わることを確かめた。",
         "exps": ["053", "054"]},
        {"name": "blendshapes::2.0", "kind": "SOP",
         "one": "複数の形を混ぜる。",
         "what": "同じ点の数を持つ形どうしを、割合を決めて混ぜる。表情の作り分けなどに使う。",
         "params": [["selectionidx", "何番目を混ぜるか"], ["diff", "差分として扱う"]]},
    ],
    "groom": [
        {"name": "guidedeform", "kind": "SOP",
         "one": "ガイドの動きに毛をついていかせる。",
         "what": "少ない本数のガイドを動かし、その動きを本数の多い毛に伝える。全部の毛を計算しなくて済むので軽い。",
         "params": [["method", "伝え方"], ["singleguide", "一番近いガイドだけを見る"]],
         "exps": ["044"]},
    ],
    "obj": [
        {"name": "geo", "kind": "OBJ",
         "one": "形を入れる箱。",
         "what": "SOP はこの中に入る。シーンの中での位置や向きは、この箱が持つ。",
         "params": [["t", "位置"], ["r", "向き"], ["s", "大きさ"]]},
        {"name": "cam", "kind": "OBJ",
         "one": "カメラ。",
         "what": "どこから、どの範囲を写すかを決める。焦点距離を短くすると広く写り、長くすると狭く大きく写る。",
         "params": [["t", "位置"], ["r", "向き"], ["focal", "焦点距離"], ["res", "画の大きさ"]],
         "exps": ["087"]},
        {"name": "hlight", "kind": "OBJ",
         "one": "光を置く。",
         "what": "点光源・面光源・平行光などを選べる。明るさと色、影の出方を決める。",
         "params": [["light_type", "光の種類"], ["light_intensity", "明るさ"], ["light_color", "色"]],
         "exps": ["088"]},
        {"name": "null", "kind": "OBJ",
         "one": "形を持たない目印。",
         "what": "位置と向きだけを持つ。他のものをぶら下げる親として使う。",
         "params": [["t", "位置"], ["r", "向き"]]},
        {"name": "subnet", "kind": "OBJ",
         "one": "複数の箱をひとまとめにする。",
         "what": "中に複数の geo やライトを入れて、まとめて動かせる。散らかったシーンを整理するのに使う。",
         "params": [["t", "位置"], ["r", "向き"]]},
        {"name": "ambient", "kind": "OBJ",
         "one": "全体をうっすら明るくする光。",
         "what": "向きの無い光で、影の中も少し見えるようにする。影が真っ黒になるのを避けたいときに足す。",
         "params": [["light_intensity", "明るさ"], ["light_color", "色"]]},
    ],
    "rop": [
        {"name": "opengl", "kind": "ROP",
         "one": "画面に見えているものを、そのまま画像に落とす。",
         "what": "光の計算をしないぶん速い。形が合っているかを確かめる用途に向く。",
         "params": [["camera", "使うカメラ"], ["trange", "出す範囲"], ["picture", "出力先"]],
         "exps": ["018"]},
        {"name": "geometry", "kind": "ROP",
         "one": "形をファイルに書き出す。",
         "what": "bgeo や obj などで保存する。連番で出せば、動く形もそのまま残せる。",
         "params": [["sopoutput", "出力先"], ["trange", "出す範囲"]],
         "exps": ["058"]},
        {"name": "alembic", "kind": "ROP",
         "one": "Alembic 形式で書き出す。",
         "what": "他のソフトへ形と動きを渡すときの定番。材質は持っていかない。",
         "params": [["filename", "出力先"], ["trange", "出す範囲"], ["build_from_path", "階層を作る"]],
         "exps": ["058"]},
        {"name": "filmboxfbx", "kind": "ROP",
         "one": "FBX 形式で書き出す。",
         "what": "ゲームエンジンへ渡すときによく使う。骨と皮も持っていける。",
         "params": [["sopoutput", "出力先"], ["startnode", "書き出す元"]]},
        {"name": "karma", "kind": "ROP",
         "one": "光を計算して絵にする。",
         "what": "反射や影を計算するので、opengl よりずっと遅いが、見た目は本物に近い。",
         "params": [["camera", "使うカメラ"], ["picture", "出力先"], ["samplesperpixel", "1画素あたりの試行回数"]],
         "exps": ["018", "038"]},
        {"name": "comp", "kind": "ROP",
         "one": "画像の合成結果を書き出す。",
         "what": "COP で組んだ画像処理の結果をファイルにする。",
         "params": [["coppath", "元になる COP"], ["copoutput", "出力先"]]},
    ],
    "vop": [
        {"name": "principledshader::2.0", "kind": "VOP",
         "one": "見た目のほとんどを1つで決める材質。",
         "what": "色・粗さ・金属らしさ・透明度などをまとめて持つ。ふだんの材質はこれ1つで足りることが多い。",
         "params": [["basecolor", "地の色"], ["rough", "粗さ。小さいほど鏡に近い"], ["metallic", "金属らしさ"], ["ior", "屈折率"]],
         "exps": ["038", "039"]},
        {"name": "texture::2.0", "kind": "VOP",
         "one": "画像を読み込んで色にする。",
         "what": "UV の座標を手がかりに、画像から色を拾う。色のほか、凹凸や粗さの元としても使う。",
         "params": [["map", "画像のファイル"], ["wrap", "はみ出したときの扱い"], ["filter", "ぼかし方"]]},
        {"name": "rampparm", "kind": "VOP",
         "one": "値から色や数への変換表を作る。",
         "what": "0から1の入力を、好きな色や数に置き換える。温度から炎の色を作るときなどに使う。",
         "params": [["parmname", "つまみの名前"], ["rampcolordefault", "既定の並び"]],
         "exps": ["026"]},
        {"name": "aanoise", "kind": "VOP",
         "one": "きめの粗さを指定できるノイズ。",
         "what": "画面の細かさに合わせてちらつきを抑える作りになっている。材質の模様に使うノイズはたいていこれ。",
         "params": [["freq", "細かさ"], ["amp", "振れ幅"], ["rough", "重ねたときの効き方"], ["maxoctave", "重ねる回数"]],
         "exps": ["004"]},
        {"name": "curlnoise", "kind": "VOP",
         "one": "渦を巻く向きを作るノイズ。",
         "what": "湧き出しも吸い込みも起きない向きの場を作る。煙や粒を自然に渦巻かせたいときに使う。",
         "params": [["freq", "渦の細かさ"], ["amp", "強さ"], ["type", "ノイズの種類"]]},
        {"name": "cellnoise", "kind": "VOP",
         "one": "区画ごとに値が変わるノイズ。",
         "what": "地面のひび割れや、石畳のような模様の元になる。滑らかに変わるのではなく、区画で切り替わる。",
         "params": [["sfreq", "横の細かさ"], ["tfreq", "縦の細かさ"], ["sjitter", "区画のずれ"]]},
    ],
}

GROUPS_NEW = [
    ("pop", "粒を動かす",
     "たくさんの小さなものを飛ばす道具。生む口・力・条件で選ぶ箱・消す箱を並べて組む。"),
    ("force", "力を足す・受け止める",
     "動いているものに外から働きかける道具。重力・抵抗・風と、ぶつかる相手。"),
    ("obj", "シーンに置く",
     "形・カメラ・光を、場面の中のどこに置くかを決める階層。"),
    ("rop", "外へ出す",
     "絵やファイルとして書き出す道具。"),
    ("vop", "材質とノイズ",
     "見た目を作る道具。色と粗さを決める材質と、模様の元になるノイズ。"),
]
